services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
      - TZ=Asia/Kolkata
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=false
      - WEBHOOK_URL=https://multilaminated-tracie-welcomingly.ngrok-free.dev/
      - N8N_EDITOR_BASE_URL=https://multilaminated-tracie-welcomingly.ngrok-free.dev/
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data:
    external: true
    name: thirsty-shaw-ed089c_n8n_data
