// Career Scout — Resume Template
// Generated by forge/forge.py — do not edit this file directly.
// All content is substituted by Python before compilation.
//
// Compile: typst compile resume.typ output.pdf

#set page(
  paper: "us-letter",
  margin: (x: 0.45in, y: 0.25in),
)

#set text(
  font: ("Linux Libertine", "Liberation Serif", "Times New Roman"),
  size: 10pt,
  fallback: true,
)

#set par(leading: 0.45em, justify: false, spacing: 0.7em)

#show heading.where(level: 1): it => {
  v(10pt, weak: true)
  text(weight: "bold", style: "italic", size: 11.5pt)[#it.body]
  v(-6pt)
  line(length: 100%, stroke: 0.5pt)
  v(5pt)
}

// ── HEADER ────────────────────────────────────────────────────────────────────
#align(center)[
  #text(size: 22pt, weight: "bold")[<<NAME>>]
  #linebreak()
  #v(3pt)
  #text(size: 10pt)[<<CONTACT_LINE>>]
]

// ── SUMMARY ───────────────────────────────────────────────────────────────────
= Summary

<<SUMMARY>>

// ── EDUCATION ─────────────────────────────────────────────────────────────────
= Education

<<EDUCATION_BLOCK>>

// ── SKILLS ────────────────────────────────────────────────────────────────────
= Skills

<<SKILLS_BLOCK>>

// ── PROJECTS ──────────────────────────────────────────────────────────────────
= Projects

<<PROJECTS_BLOCK>>

// ── INTERNSHIPS ───────────────────────────────────────────────────────────────
= Internships

<<EXPERIENCE_BLOCK>>

<<CERTIFICATIONS_BLOCK>>
