// Career Scout — Resume Template
// Generated by forge/forge.py — do not edit this file directly.
// All content is substituted by Python before compilation.
//
// Compile: typst compile resume.typ output.pdf

#set page(
  paper: "us-letter",
  margin: (x: 0.55in, y: 0.45in),
)

#set text(
  font: ("Linux Libertine", "Liberation Serif", "Times New Roman"),
  size: 10.5pt,
  fallback: true,
)

#set par(leading: 0.52em, justify: false)

#show heading.where(level: 1): it => {
  v(5pt)
  text(weight: "bold", size: 11pt)[#it.body]
  v(-4pt)
  line(length: 100%, stroke: 0.6pt)
  v(1pt)
}

#show heading.where(level: 2): it => {
  v(3pt)
  text(weight: "bold")[#it.body]
}

// ── HEADER ────────────────────────────────────────────────────────────────────
#align(center)[
  #text(size: 20pt, weight: "bold")[<<NAME>>]
  #linebreak()
  #text(size: 10pt)[
    <<LOCATION>> #h(6pt) | #h(6pt) <<EMAIL>> #h(6pt) | #h(6pt) <<PHONE>>
    #linebreak()
    <<LINKEDIN>> #h(6pt) | #h(6pt) <<GITHUB>>
  ]
]

#v(4pt)

// ── SUMMARY ───────────────────────────────────────────────────────────────────
= Summary

<<SUMMARY>>

// ── SKILLS ────────────────────────────────────────────────────────────────────
= Skills

<<SKILLS_BLOCK>>

// ── EDUCATION ─────────────────────────────────────────────────────────────────
= Education

== <<ED_DEGREE>> | <<ED_INSTITUTION>>

#text(style: "italic")[<<ED_DATES>>] #h(1fr) GPA: <<ED_GPA>>

<<ED_HIGHLIGHTS>>

// ── EXPERIENCE ────────────────────────────────────────────────────────────────
= Experience

<<EXPERIENCE_BLOCK>>

// ── PROJECTS ──────────────────────────────────────────────────────────────────
= Projects

<<PROJECTS_BLOCK>>

// ── CERTIFICATIONS ────────────────────────────────────────────────────────────
<<CERTIFICATIONS_BLOCK>>
